### ISSUE TITLE
Issue with puppeteer and Netlify 

### ISSUE THREAD

**Issue by jbrialon** [jbrialon/photo#39]
```
11:16:07 AM: Build command from Netlify app                                
11:16:07 AM: ────────────────────────────────────────────────────────────────
11:16:07 AM: ​
11:16:07 AM: $ npm run build
11:16:07 AM: > completementalest@2.0.0 build
11:16:07 AM: > vite build
11:16:08 AM: vite v5.0.11 building for production...
11:16:08 AM: transforming...
11:16:10 AM: ✓ 345 modules transformed.
11:16:10 AM: rendering chunks...
11:16:11 AM: Failed during stage "building site": Build script returned non-zero exit code: 2
11:16:11 AM: [plugin:Prerender Plugin] Unable to prerender all routes!
11:16:11 AM: [Prerender Plugin] Could not find Chrome (ver. 119.0.6045.105). This can occur if either
11:16:11 AM:  1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
11:16:11 AM:  2. your cache path is incorrectly configured (which is: /opt/buildhome/.cache/puppeteer).
11:16:11 AM: For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
11:16:11 AM: ✓ built in 2.97s
11:16:11 AM: error during build:
11:16:11 AM: RollupError: Could not find Chrome (ver. 119.0.6045.105). This can occur if either
11:16:11 AM:  1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
11:16:11 AM:  2. your cache path is incorrectly configured (which is: /opt/buildhome/.cache/puppeteer).
11:16:11 AM: For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
11:16:11 AM:     at error (file:///opt/build/repo/node_modules/vite/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
11:16:11 AM:     at Object.error (file:///opt/build/repo/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:18485:20)
11:16:11 AM:     at Object.<anonymous> (/opt/build/repo/node_modules/@prerenderer/rollup-plugin/dist/RollupPrerenderPlugin.js:140:34)
11:16:11 AM:     at Generator.throw (<anonymous>)
11:16:11 AM:     at rejected (/opt/build/repo/node_modules/@prerenderer/rollup-plugin/dist/RollupPrerenderPlugin.js:29:65)
11:16:11 AM: ​
11:16:11 AM: "build.command" failed                                        
```

**Comment by jbrialon** [comment]
found the solution: https://www.zachleat.com/web/chromium-missing/
